name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Проверка клиентской части

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jre-headless
        pip install html5validator

    - name: Проверка client.html
      run: |
        html5validator --root . --also-check-css --show-warnings --ignore "attribute ‘loading’ not allowed" --no-langdetect

  test-backend:
    runs-on: ubuntu-latest
    name: Сборка и тестирование серверной части

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Установка зависимостей
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install flask flask_sqlalchemy flask_migrate flask-cors psycopg2-binary

    - name: Инициализация БД
      env:
        FLASK_APP: server.py
      run: |
        source venv/bin/activate
        flask db init || true
        flask db migrate -m "CI migration" || true
        flask db upgrade

    - name: Проверка запуска Flask API
      run: |
        source venv/bin/activate
        FLASK_APP=server.py flask run --host=127.0.0.1 --port=5000 &
        sleep 5
        curl -f http://127.0.0.1:5000/products || exit 1
